version: '3.8'

services:
  nuxt-ssr:
    container_name: levelup-frontend-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    develop:
      watch:
        - action: sync
          path: ./
          target: /app/
          ignore:
            - node_modules/
            - .nuxt/
            - .output/
            - dist/
        - action: rebuild
          path: ./package.json
          target: /app/package.json
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      NUXT_PORT: 3000
      NUXT_PUBLIC_API_BASE_URL: http://localhost:4000
      NUXT_API_BASE_URL: http://levelup-backend:4000
      CHOKIDAR_USEPOLLING: 'true'  # Enable polling for file changes (required for hot reload)
    command: npm run dev
    networks:
      - levelup-network
networks:
  levelup-network:
    external: true  # Use the existing external network shared with the backend
